### ISSUE TITLE
libRuntime.so!Runtime::instantiateModule Unhandled runtime exception: wavm.invalidSegmentOffset parsing running wasm file causing crash 

### ISSUE THREAD

**Issue by zhongyinglou** [AndrewScheidecker/WAVM#95] opened 2018-07-26 13:08 UTC
[runtime exception wavm.invalidSegmentOffset15_1.zip](https://github.com/AndrewScheidecker/WAVM/files/2232065/runtime.exception.wavm.invalidSegmentOffset15_1.zip)

**Comment by AndrewScheidecker** [comment] 2018-07-26 14:52
Thanks, this is fixed by https://github.com/AndrewScheidecker/WAVM/commit/c2939744b1aea12a248705b2d83734b927835d9b

**Closed by AndrewScheidecker** 2018-07-26 14:52 UTC

**Comment by AndrewScheidecker** [comment] 2018-07-26 15:43
Oops, this was not fixed by that change. However, this is not a bug. Throwing a runtime exception when the segment offset is invalid is the expected behavior.
